stages:
  - threestages

variables:
  TF_VERSION: "1.0.9"  # Define the Terraform version you want to install

before_script:
  - sudo apt update && sudo apt install -y curl unzip  # Install necessary tools (for Alpine-based images)
  - curl -fsSL "https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip" -o terraform.zip
  - unzip terraform.zip
  - chmod +x terraform
  - mv terraform /usr/local/bin/terraform
  - terraform --version  # Verify Terraform installation

threestages:
  stage: threestages
  script:
    - terraform init
    - terraform plan -var-file=dev.tfvars
    - terraform apply -var-file=dev.tfvars -auto-approve

